### ISSUE TITLE
When Using Specific Armors Crash the Game

### ISSUE THREAD

**Issue by linfoxgamer** [devs-immortal/The-Aether#133]
Using Gravitite,Obsidian or Neptune Armor Crashes the Game

```python
[09:35:52] [main/FATAL]: Reported exception thrown!
net.minecraft.class_148: Rendering entity in world
	at net.minecraft.class_757.method_3192(class_757.java:625) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1048) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:681) [intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:215) [intermediary-minecraft-1.16.5-client.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_275]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_275]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_275]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_275]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226) [fabric-loader-0.11.3.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146) [fabric-loader-0.11.3.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.3.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_275]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_275]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_275]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_275]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: software.bernie.geckolib3.geo.exception.GeckoLibException: the_aether:geo/gravitite_armor.geo.json: Could not find model. If you are getting this with a built mod, please just restart your game.
	at software.bernie.geckolib3.model.AnimatedGeoModel.getModel(AnimatedGeoModel.java:104) ~[geckolib-fabric-1.16.5-3.0.23.jar:?]
	at software.bernie.geckolib3.renderer.geo.GeoArmorRenderer.applySlot(GeoArmorRenderer.java:187) ~[geckolib-fabric-1.16.5-3.0.23.jar:?]
	at software.bernie.geckolib3.item.GeoArmorItem.getArmorModel(GeoArmorItem.java:25) ~[geckolib-fabric-1.16.5-3.0.23.jar:?]
	at software.bernie.geckolib3.ArmorRenderingRegistryImpl.getArmorModel(ArmorRenderingRegistryImpl.java:25) ~[geckolib-fabric-1.16.5-3.0.23.jar:?]
	at net.minecraft.class_970.handler$zcp000$selectArmorModel(class_970.java:568) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_970.method_4172(class_970.java:110) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_970.method_17157(class_970.java:37) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_970.method_4199(class_970.java:22) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_922.method_4054(class_922.java:139) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_1007.method_4215(class_1007.java:65) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_1007.method_3936(class_1007.java:42) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_898.method_3954(class_898.java:261) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_490.method_29977(class_490.java:149) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.runAsFancy(RenderSystem.java:1439) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_490.method_2486(class_490.java:149) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_481.method_2389(class_481.java:763) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_465.method_25394(class_465.java:101) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_485.method_25394(class_485.java:542) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_481.method_25394(class_481.java:677) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:616) ~[intermediary-minecraft-1.16.5-client.jar:?]
	... 18 more
---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 3/15/21 9:35 AM
Description: Rendering entity in world

software.bernie.geckolib3.geo.exception.GeckoLibException: the_aether:geo/gravitite_armor.geo.json: Could not find model. If you are getting this with a built mod, please just restart your game.
	at software.bernie.geckolib3.model.AnimatedGeoModel.getModel(AnimatedGeoModel.java:104)
	at software.bernie.geckolib3.renderer.geo.GeoArmorRenderer.applySlot(GeoArmorRenderer.java:187)
	at software.bernie.geckolib3.item.GeoArmorItem.getArmorModel(GeoArmorItem.java:25)
	at software.bernie.geckolib3.ArmorRenderingRegistryImpl.getArmorModel(ArmorRenderingRegistryImpl.java:25)
	at net.minecraft.class_970.handler$zcp000$selectArmorModel(class_970.java:568)
	at net.minecraft.class_970.method_4172(class_970.java:110)
	at net.minecraft.class_970.method_17157(class_970.java:37)
	at net.minecraft.class_970.method_4199(class_970.java:22)
	at net.minecraft.class_922.method_4054(class_922.java:139)
	at net.minecraft.class_1007.method_4215(class_1007.java:65)
	at net.minecraft.class_1007.method_3936(class_1007.java:42)
	at net.minecraft.class_898.method_3954(class_898.java:261)
	at net.minecraft.class_490.method_29977(class_490.java:149)
	at com.mojang.blaze3d.systems.RenderSystem.runAsFancy(RenderSystem.java:1439)
	at net.minecraft.class_490.method_2486(class_490.java:149)
	at net.minecraft.class_481.method_2389(class_481.java:763)
	at net.minecraft.class_465.method_25394(class_465.java:101)
	at net.minecraft.class_485.method_25394(class_485.java:542)
	at net.minecraft.class_481.method_25394(class_481.java:677)
	at net.minecraft.class_757.method_3192(class_757.java:616)
	at net.minecraft.class_310.method_1523(class_310.java:1048)
	at net.minecraft.class_310.method_1514(class_310.java:681)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at software.bernie.geckolib3.model.AnimatedGeoModel.getModel(AnimatedGeoModel.java:104)
	at software.bernie.geckolib3.renderer.geo.GeoArmorRenderer.applySlot(GeoArmorRenderer.java:187)
	at software.bernie.geckolib3.item.GeoArmorItem.getArmorModel(GeoArmorItem.java:25)
	at software.bernie.geckolib3.ArmorRenderingRegistryImpl.getArmorModel(ArmorRenderingRegistryImpl.java:25)
	at net.minecraft.class_970.handler$zcp000$selectArmorModel(class_970.java:568)
	at net.minecraft.class_970.method_4172(class_970.java:110)
	at net.minecraft.class_970.method_17157(class_970.java:37)
	at net.minecraft.class_970.method_4199(class_970.java:22)
	at net.minecraft.class_922.method_4054(class_922.java:139)
	at net.minecraft.class_1007.method_4215(class_1007.java:65)
	at net.minecraft.class_1007.method_3936(class_1007.java:42)

-- Entity being rendered --
Details:
	Entity Type: minecraft:player (net.minecraft.class_746)
	Entity ID: 215
	Entity Name: lin_fox
	Entity's Exact location: 17.10, 129.75, 1.59
	Entity's Block location: World: (17,129,1), Chunk: (at 1,8,1 in 1,0; contains blocks 16,0,0 to 31,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null

-- Renderer details --
Details:
	Assigned renderer: net.minecraft.class_1007@6818366a
	Location: 0.00,0.00,0.00 - World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Rotation: 0.0
	Delta: 1.0
Stacktrace:
	at net.minecraft.class_898.method_3954(class_898.java:261)
	at net.minecraft.class_490.method_29977(class_490.java:149)
	at com.mojang.blaze3d.systems.RenderSystem.runAsFancy(RenderSystem.java:1439)
	at net.minecraft.class_490.method_2486(class_490.java:149)
	at net.minecraft.class_481.method_2389(class_481.java:763)
	at net.minecraft.class_465.method_25394(class_465.java:101)
	at net.minecraft.class_485.method_25394(class_485.java:542)
	at net.minecraft.class_481.method_25394(class_481.java:677)

-- Screen render details --
Details:
	Screen name: net.minecraft.class_481
	Mouse location: Scaled: (313, 216). Absolute: (627.000000, 432.000000)
	Screen size: Scaled: (680, 335). Absolute: (1360, 670). Scale factor of 2.000000

-- Affected level --
Details:
	All players: 1 total; [class_746['lin_fox'/215, l='ClientLevel', x=17.10, y=129.75, z=1.59]]
	Chunk stats: SodiumChunkCache: 225
	Level dimension: the_aether:the_aether
	Level spawn location: World: (32,63,80), Chunk: (at 0,3,0 in 2,5; contains blocks 32,0,80 to 47,255,95), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 11262 game time, 11262 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:449)
	at net.minecraft.class_310.method_1587(class_310.java:2239)
	at net.minecraft.class_310.method_1514(class_310.java:699)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
```

**Comment by Jack-Papel** [comment]
This is known. It's because they don't yet have models

**Comment by linfoxgamer** [comment]
Thanks

Em seg., 15 de mar. de 2021 às 17:03, Jack Papel ***@***.***>
escreveu:
