### ISSUE TITLE
Chunks with structures fail to save

### ISSUE THREAD

**Issue by Cynosphere** [devs-immortal/The-Aether#206]
<details>
<summary>Stacktrace</summary>
<pre>
[10:46:48] [Server thread/ERROR]: Failed to save chunk 1,-13
java.lang.NullPointerException: null
	at net.minecraft.class_3443.method_14946(class_3443.java:93) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_3449.method_14972(class_3449.java:110) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_2852.method_12385(class_2852.java:407) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_2852.method_12410(class_2852.java:359) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_3898.method_17228(class_3898.java:716) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_3898.method_20583(class_3898.java:388) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:1.8.0_292]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_292]
	at java.util.Iterator.forEachRemaining(Iterator.java:116) ~[?:1.8.0_292]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:1.8.0_292]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_292]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_292]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:1.8.0_292]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:1.8.0_292]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_292]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485) ~[?:1.8.0_292]
	at net.minecraft.class_3898.method_17242(class_3898.java:385) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_3215.method_17298(class_3215.java:321) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_3218.method_14176(class_3218.java:710) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_3723(MinecraftServer.java:567) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_1132.method_3748(class_1132.java:83) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:670) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
</pre>
</details>

**Comment by DaisukeVN** [comment]
I can confirm this issue and waiting 'til the bugfix will release. This Error isn't useful for public Server...

**Comment by kalucky0** [comment]
It's already resolved. Just wait for Beta 1.0.4
