### ISSUE TITLE
Moa Eggs crash the game when placed

### ISSUE THREAD

**Issue by UnusedCactus** [devs-immortal/The-Aether#327]
Moa eggs, when placed on the ground, crash the game instead of placing the egg.

**Comment by Jack-Papel** [comment]
Could you provide a crash report?

**Comment by UnusedCactus** [comment]
I just placed a Moa egg, and then the game crashed. The error code was -1. I'll get the crash report soon.

**Comment by UnusedCactus** [comment]
_**Here's the crash report.**_
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.aether.items.MoaEgg.method_7884(MoaEgg.java:30)
	at net.minecraft.class_1799.method_7981(class_1799.java:244)
	at net.minecraft.class_636.method_2896(class_636.java:338)
	at net.minecraft.class_310.method_1583(class_310.java:1648)
	at net.minecraft.class_310.method_1508(class_310.java:1902)

-- Affected level --
Details:
	All players: 1 total; [class_746['UnusedCactus'/94, l='ClientLevel', x=-826.17, y=56.00, z=465.18]]
	Chunk stats: 841, 576
	Level dimension: the_aether:the_aether
	Level spawn location: World: (-144,77,-79), Section: (at 0,13,1 in -9,4,-5; chunk contains blocks -144,0,-80 to -129,383,-65), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,383,-1)
	Level time: 182566 game time, 1 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:370)
	at net.minecraft.class_310.method_1587(class_310.java:2399)
	at net.minecraft.class_310.method_1514(class_310.java:754)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods
