### ISSUE TITLE
Minegate incompatibility

### ISSUE THREAD

**Issue by HypixionGaming** [devs-immortal/The-Aether#449]
This is the log

```[20:19:04] [Render thread/ERROR]: Feature: Not a JSON object: "the_aether:flutegrass"; Not a JSON object: "the_aether:sparse_trees"; Not a JSON object: "the_aether:patch_blueberry"; Not a JSON object: "the_aether:water_spring"; Not a JSON object: "the_aether:aether_tall_grass"; Not a JSON object: "the_aether:aether_grass"; Not a JSON object: "the_aether:aether_flowers"
[20:19:04] [Render thread/ERROR]: Feature: Not a JSON object: "the_aether:flutegrass"; Not a JSON object: "the_aether:alt_fallen_leaves"; Not a JSON object: "the_aether:aether_fern"; Not a JSON object: "the_aether:water_spring"; Not a JSON object: "the_aether:scattered_trees"; Not a JSON object: "the_aether:patch_blueberry"; Not a JSON object: "the_aether:aether_dense_tall_grass"; Not a JSON object: "the_aether:aether_bush"; Not a JSON object: "the_aether:aether_grass"; Not a JSON object: "the_aether:aether_tall_grass"; Not a JSON object: "the_aether:aether_flowers"
[20:19:05] [Render thread/ERROR]: Feature: Not a JSON object: "the_aether:sparse_trees"; Not a JSON object: "the_aether:thicket_trees"; Not a JSON object: "the_aether:aether_dense_fern"; Not a JSON object: "the_aether:aether_dense_bush"; Not a JSON object: "the_aether:water_spring"; Not a JSON object: "the_aether:aether_tall_grass"; Not a JSON object: "the_aether:fallen_leaves"; Not a JSON object: "the_aether:aether_grass"; Not a JSON object: "the_aether:aether_flowers"
[20:19:05] [Render thread/ERROR]: Feature: Not a JSON object: "the_aether:wisteria_woods_trees"; Not a JSON object: "the_aether:patch_blueberry"; Not a JSON object: "the_aether:aether_bush"; Not a JSON object: "the_aether:rainbow_fallen_leaves"; Not a JSON object: "the_aether:aether_fern"; Not a JSON object: "the_aether:aether_grass"; Not a JSON object: "the_aether:aether_flowers"
[20:19:05] [Render thread/WARN]: Failed to validate datapack
java.util.concurrent.CompletionException: com.google.gson.JsonParseException: Error loading registry data: No key Properties in MapLike[{"Name":"the_aether:aether_bush"}]
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314) [?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319) [?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) [?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) [?:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:151) [intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) [intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:125) [intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:110) [intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1075) [intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:728) [intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:217) [intermediary-minecraft-1.17.1-client.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.6.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: com.google.gson.JsonParseException: Error loading registry data: No key Properties in MapLike[{"Name":"the_aether:aether_bush"}]
	at net.minecraft.class_5455.method_34849(class_5455.java:221) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at net.minecraft.class_5455.method_30526(class_5455.java:221) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_5455.method_30519(class_5455.java:212) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_5382.method_36575(class_5382.java:57) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_5382.method_36574(class_5382.java:51) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_5292.method_31132(class_5292.java:319) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_525.method_37088(class_525.java:459) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) ~[?:?]
	... 23 more
```

**Comment by HypixionGaming** [comment]
This inhibits world loading/creation

**Comment by Jack-Papel** [comment]
Version info:
Trinkets 3.0.2
Aether release 1.5.0
Fabric API 0.37.1
Minecraft 1.17.1
MultiMC OneSix Launcher

**Comment by HypixionGaming** [comment]
Link to Minegate for those that need it: https://www.curseforge.com/minecraft/mc-mods/minegate-moreblocks

**Comment by Jack-Papel** [comment]
From the Minegate author:

>This is an incompatibility with other mods that affect the generation of worlds.
>For this, you have the option to disable MoreBlocks mixins in settings, available with Mod Menu or in « .minecraft/config/minegate.json » by putting the option « useMixins » on false.
>
>This disables the possibility of placing grass, flowers or snow on the plantable slabs.
>
>Have a good day :)

**Comment by CDAGaming** [comment]
Pinning and locking as external incompatibility, and for future users.
