### ISSUE TITLE
Crash: Multiplayer server crash (mod incompatibility with Harvest scythes mod)

### ISSUE THREAD

**Issue by serioos** [devs-immortal/The-Aether#553]
### What were you doing when the crash occured?

The latest version of Aether mod is incompatible with the Harvest Scythes mod and causes the server to crash on start up.

Log: https://pastebin.com/fLWZN7CG
Modlist: https://pastebin.com/JAwfcAWa

### Did it crash the client or server?

Server

### Mod Version

1.6.1

### Fabric API Version

fabric-api-0.43.1+1.17

### Trinkets Version

trinkets-3.0.4

### Crash Report

```shell
[15:39:53] [main/INFO]: [Aether Reborn] detected. Loading supported items.
[15:39:53] [main/INFO]: [STDERR]: java.lang.RuntimeException: Failed to setup Fabric server environment!
[15:39:53] [main/INFO]: [STDERR]: at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:62)
[15:39:53] [main/INFO]: [STDERR]: Caused by: java.lang.RuntimeException: java.lang.RuntimeException: An exception occurred when launching the server!
[15:39:53] [main/INFO]: [STDERR]: at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:100)
[15:39:53] [main/INFO]: [STDERR]: at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:60)
[15:39:53] [main/INFO]: [STDERR]: Caused by: java.lang.RuntimeException: An exception occurred when launching the server!
[15:39:53] [main/INFO]: [STDERR]: at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:74)
[15:39:53] [main/INFO]: [STDERR]: at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:98)
[15:39:53] [main/INFO]: [STDERR]: ... 1 more
[15:39:53] [main/INFO]: [STDERR]: Caused by: java.lang.reflect.InvocationTargetException
[15:39:53] [main/INFO]: [STDERR]: at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[15:39:53] [main/INFO]: [STDERR]: at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
[15:39:53] [main/INFO]: [STDERR]: at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[15:39:53] [main/INFO]: [STDERR]: at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[15:39:53] [main/INFO]: [STDERR]: at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:72)
[15:39:53] [main/INFO]: [STDERR]: ... 2 more
[15:39:53] [main/INFO]: [STDERR]: Caused by: java.lang.RuntimeException: Minecraft has crashed
[15:39:53] [main/INFO]: [STDERR]: at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:571)
[15:39:53] [main/INFO]: [STDERR]: at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
[15:39:53] [main/INFO]: [STDERR]: at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23)
[15:39:53] [main/INFO]: [STDERR]: ... 7 more
[15:39:53] [main/INFO]: [STDERR]: Caused by: java.lang.NoClassDefFoundError: com/aether/items/utils/AetherTiers
[15:39:53] [main/INFO]: [STDERR]: at wraith.harvest_scythes.support.AetherSupport.loadItems(AetherSupport.java:15)
[15:39:53] [main/INFO]: [STDERR]: at wraith.harvest_scythes.HarvestScythes.load(HarvestScythes.java:112)
[15:39:53] [main/INFO]: [STDERR]: at net.minecraft.server.Main.handler$cij000$inject(Main.java:2015)
[15:39:53] [main/INFO]: [STDERR]: at net.minecraft.server.Main.main(Main.java:99)
[15:39:53] [main/INFO]: [STDERR]: at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[15:39:53] [main/INFO]: [STDERR]: at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
[15:39:53] [main/INFO]: [STDERR]: at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[15:39:53] [main/INFO]: [STDERR]: at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[15:39:53] [main/INFO]: [STDERR]: at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:568)
[15:39:53] [main/INFO]: [STDERR]: ... 9 more
[15:39:53] [main/INFO]: [STDERR]: Caused by: java.lang.ClassNotFoundException: com.aether.items.utils.AetherTiers
[15:39:53] [main/INFO]: [STDERR]: at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:636)
[15:39:53] [main/INFO]: [STDERR]: at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:182)
[15:39:53] [main/INFO]: [STDERR]: at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
[15:39:53] [main/INFO]: [STDERR]: at net.fabricmc.loader.impl.launch.server.InjectingURLClassLoader.loadClass(InjectingURLClassLoader.java:57)
[15:39:53] [main/INFO]: [STDERR]: at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
[15:39:53] [main/INFO]: [STDERR]: at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:158)
[15:39:53] [main/INFO]: [STDERR]: at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
[15:39:53] [main/INFO]: [STDERR]: ... 18 more
```

### Other mods

```shell
1.17.1-additionalbars-2.1.1.jar
adapaxels-1.2.2+1.17.1.jar
AdditionalAdditions-2.2.0.jar
Adorn-2.3.1+1.17.1-fabric.jar
adventurez-1.4.3.jar
aether-1.17.1-1.6.1.jar
animal_feeding_trough-1.0.2.jar
antighost-1.17.1-fabric0.36.1-1.1.4.jar
arcanus-1.23.jar
architectury-2.6.35.jar
artifality-0.4.3-fabric.jar
attribute-fix-fabric-1.17.1-1.0.3.jar
autoconfig1u-3.3.1.jar
AwesomeDungeonFabric-1.17.1-1.1.2.jar
axolotl-item-fix-1.1.3.jar
backslot-1.2.2.jar
bclib-0.5.3.jar
beenfo-1.17.1-fabric0.36.1-1.3.2.jar
better-end-0.12.4.jar
better-nether-5.3.11.jar
BetterDungeons-Fabric-1.17-1.0.2.jar
BetterMineshafts-Fabric-1.17-1.0.1.jar
BetterStrongholds-Fabric-1.17-1.1.2.jar
betterthanmending-1.3.0.jar
bewitchment-1.17-14.jar
bitsandchisels-2.6.0.jar
blast-1.8.1.jar
blockus-2.2.10+1.17.1.jar
BOMD-1.3.2-1.17.1.jar
BowInfinityFix-1.17.x-fabric-rv10.jar
caelus-fabric-0.0.18-1.17.1.jar
campanion-2.0.1.jar
Cardinal-Components-API-3.1.1.jar
carrier-1.8.2.jar
charm-fabric-1.17-3.3.2.jar
CHAS-1.17-1.7-Fabric.jar
cleancut-1.17-4.0-fabric.jar
cloth-api-2.0.54.jar
cloth-config-5.1.40-fabric.jar
Clumps-fabric-1.17.1-7.0.10.jar
columns-1.2.0.jar
comforts-fabric-0.0.7-1.17.1.jar
companion-bats-fabric-1.18.4.jar
convenient-mobgriefing-2.0.2.jar
Couplings-1.6.0+1.17.jar
crawl-0.9.3.jar
Croptopia-1.17.1-FABRIC-1.7.0.jar
dark-enchanting-0.6.0-1.17.1.jar
DarkPaintings-fabric-1.17.1-4.0.2.jar
dataattributes-1.0.6-1.17.1.jar
dawn-2.0.6.jar
deepslatecutting-1.2.2.jar
dragonloot-1.0.9.jar
drinkbeer-v2.3 for 1.17.1.jar
DualRiders-1.17-1.0.5.jar
DungeonsArise-1.17.1-2.1.49-fabric-release.jar
Earth2Java-1.7.3+1.17.jar
easiervillagertrading-1.17.1-fabric0.36.1-1.5.4.jar
elytratrinket-fabric-2.0.1-1.17.jar
EmeraldTools-Fabric-1.17.1-1.2.30.jar
end-goblin-traders-1.3.0.jar
enhancedcelestials-1.17.1-2.0.6.jar
ExplorersCompass-1.17.1-2.0.2-fabric.jar
extraalchemy-fabric-1.17.1-1.6.1.jar
extraorigins-1.17-10.jar
ezpas-1.2.1-1.17.1.jar
fabric-api-0.43.1+1.17.jar
fabric-branders-spawnermod-1.17.1-1.1.2.jar
fabric-enchantments-0.5.0.jar
fabric-language-kotlin-1.7.0+kotlin.1.6.0.jar
FABRIC_1.17_chipped-1.1.1.jar
FallingTree-1.17.1-2.14.3.jar
ferritecore-3.1.0-fabric.jar
Fireplace-Lib-6.2.0+1.17.1.jar
flytre-lib-1.4.2.jar
forgottenrecipes-fabric-1.17.1-1.0.3.jar
gate-of-babylon-1.5.1-1.17.1.jar
geckolib-fabric-1.17-3.0.29.jar
genesis-0.7.1.jar
glassential-fabric-1.17-1.2.0.jar
go-fish-1.3.0-beta-1.17.1.jar
Gobber2-Fabric-1.17.1-2.4.61.jar
goblin-traders-1.3.0.jar
goldenhoppers-1.1.0.jar
golemsgalore-1.0.3-1.17.1.jar
grass-pass-1.17-1.0.0.jar
grind-enchantments-1.4.0+1.17.1.jar
haema-1.7.7+1.17.jar
hydrogen-fabric-mc1.17.1-0.3.jar
icarus-1.8.jar
impaled-1.0.1.jar
impersonate-2.3.5.jar
inmis-2.3.2-1.17.1.jar
Kambrik-1.1.0.jar
krypton-0.1.4.jar
lacrimis-2.1.3+1.17.1.jar
lazydfu-0.1.2.jar
lithium-fabric-mc1.17.1-0.7.5.jar
lovely_snails-1.0.3+1.17.jar
magicfungi-0.6.0-BETA+1.17.1.jar
mcda-1.8.1.jar
mcdar-1.4.3.jar
mcdw-3.6.0.jar
medieval-origins-3.0.1.jar
medievalweapons-1.1.7.jar
megane-5.6.0.jar
mermod-1.9.jar
Mo-Glass-1.5-MC1.17.1.jar
moborigins-1.7.0.jar
mooblooms-1.5.1.jar
morevillagers-FABRIC-1.17-2.1.1.jar
mostructures-1.3.0-pre1-1.17.1-fabric.jar
mythic-mounts-1.17.1-3.0.jar
NaturesCompass-1.17.1-2.0.1-fabric.jar
nears-1.17-1.1.2.jar
notenoughcrashes-4.1.2+1.17.1-fabric.jar
observable-0.1.2-1.17-fabric.jar
Origins-1.17-1.1.4.jar
Origins-Classes-1.17-1.2.2.jar
outvoted-1.5.0-beta.4.jar
Overlord-3.0.3+1.17.1.jar
owo-lib-0.3.2+1.17.jar
oxidized-1.4.0.jar
pal-1.4.0.jar
Patchouli-1.17.1-58-FABRIC.jar
Pehkui-2.5.3+1.14.4-1.18.jar
phosphor-fabric-mc1.17.x-0.8.0.jar
pigsteel-1.6.6.jar
plantinajar-2.2.2.jar
playerex-3.0.7-1.171.jar
polymorph-fabric-0.0.14-1.17.1.jar
PresenceFootsteps-r32-1.17-rc1.jar
promenade-2.1.2.jar
quartz-elevator-1.2.5-1.17.1.jar
ratsmischief-1.3.2.jar
repurposed_structures_fabric-2.5.7+1.17.1.jar
reroll-1.3.0-1.17.1.jar
riverredux-0.2.0.jar
RoughlyEnoughItems-6.2.335.jar
Runelic-fabric-1.17.1-3.0.1.jar
scorch-1.2.0.jar
shulkerboxtooltip-3.0.4+1.17.1.jar
sit-1.17.1-13.jar
somnus-fabric-0.0.14-1.17.1.jar
spark-fabric.jar
stonevaults-1.1.0.jar
the_bumblezone_fabric-3.4.1+1.17.1.jar
things-0.2.7.jar
traverse-4.0.0.jar
trinkets-3.0.4.jar
upgradedechests-1.0.3-1.17.jar
upgradedshulkers-1.1.1.-1.17.jar
veinmining-fabric-0.0.11-1.17.1.jar
voidz-1.0.5.jar
wanderingcollector-1.0.2+mc1.17.jar
WardBlocks-Fabric-1.17.1-1.1.10.jar
windchimes-1.2.0.jar
wolves-with-armor-1.6.1-1.17.1.jar
worldedit-mod-7.2.7.jar
wraith-waystones-2.2.2.jar
wthit-fabric-3.11.2.jar
Xaeros_Minimap_21.22.2_Fabric_1.17.1.jar
XaerosWorldMap_1.18.3_Fabric_1.17.1.jar
YungsApi-1.17-Fabric-19.jar
zihlaunchpads-1.2.0.jar
```

**Comment by Suncradle** [comment]
That looks to be an issue one the other mod's side; it's looking for a class that no longer exists. Please report this issue to the harvest scythes mod.

**Comment by Jack-Papel** [comment]
Yes, suncradle is correct

**Comment by Jack-Papel** [comment]
This issue has been resolved by the creator of Harvest Scythes. Thanks for reporting.
