### ISSUE TITLE
Crash: on startup with Additional Banners

### ISSUE THREAD

**Issue by SplendidAlakey** [devs-immortal/The-Aether#669]
### What were you doing when the crash occured? How can we replicate it?

1. Install Paradise Lost, [Additional Banners](https://www.curseforge.com/minecraft/mc-mods/additional-banners) and both mods' requirements
2. Launch the game
3. Observe a crash

### Did it crash the client or server?

Client

### Mod Version

Beta 1.6.9

### Fabric API Version

0.51.1

### Crash Report

```Shell
https://gist.github.com/SplendidAlakey/9ec27c719b1cce2e4669fb51cb52384f
```

### Additional Information

I'm using MultiMC.

**Comment by gudenau** [comment]
```
Caused by: java.lang.UnsupportedOperationException: Attempted to extend inextensible enum class net.minecraft.class_1814. Create a mixin for it from the template in EnumExtender.
	at net.id.aether.util.EnumExtender.add(EnumExtender.java:23)
	at net.id.aether.items.utils.AetherRarity.<clinit>(AetherRarity.java:8)
	... 18 more
```
This is quite odd, this will have to be investigated at some point.

**Comment by SollyW** [comment]
Switch to divine intervention
