### ISSUE TITLE
Bug: Farmer Villagers can't trade nor pick up items

### ISSUE THREAD

**Issue by chorbintime** [devs-immortal/The-Aether#726]
### What happened?

A bug happened!

To replicate:
1. First, install https://www.curseforge.com/minecraft/modpacks/better-mc-fabric
2. Next, turn a villager into a farmer.
3. Next, try to interact with the farmer. It will shake its head at you.
4. Finally, delete Paradise Lost and retry with the same villagers.

### Mod Version

Beta 0.2.0 1.19.2

### Fabric API Version

0.14.10

### Relevant log output

```Shell
[19:33:23] [Server thread/INFO]: oofmas joined the game
[19:33:23] [Render thread/INFO]: New world map session initialized!
[19:33:24] [Render thread/INFO]: Started 6 worker threads
[19:33:24] [Netty Local Client IO #0/INFO]: Read 8390 bytes, 158 objects
[19:33:24] [Server thread/INFO]: Updating all forceload tickets for 264c650c-4cc1-47fd-8882-fa0f9952ff4a
[19:33:24] [Render thread/INFO]: [bclib] Auto-Sync was disabled on the client.
[19:33:24] [Render thread/WARN]: Unknown biome 'minecraft:snowy_mountains'
[19:33:24] [Render thread/WARN]: Unknown biome 'minecraft:snowy_tundra'
[19:33:24] [Render thread/WARN]: Unknown biome 'minecraft:wooded_mountains'
[19:33:24] [Render thread/WARN]: Unknown biome 'minecraft:'
[19:33:24] [Render thread/WARN]: Unknown biome 'minecraft:snowy_taiga_mountains'
[19:33:24] [Render thread/WARN]: Unknown biome 'minecraft:gravelly_mountains'
[19:33:24] [Render thread/WARN]: Unknown biome 'minecraft:wooded_hills'
[19:33:24] [Render thread/WARN]: Unknown biome 'minecraft:mountain_edge'
[19:33:24] [Render thread/WARN]: Unknown biome 'minecraft:mountains'
[19:33:24] [Netty Server IO #1/INFO]: Priority overwritten for player oofmas. Normal: GRAVE / Robbing: INVENTORY
[19:33:24] [Render thread/INFO]: Synced immersive_weathering-common.json configs
[19:33:24] [Render thread/INFO]: Received config from the server: 
[19:33:24] [Render thread/INFO]: Synced supplementaries-common.json configs
[19:33:24] [Render thread/INFO]: Synced Flute Songs
[19:33:24] [Render thread/INFO]: Synced Captured Mobs settings
[19:33:24] [Render thread/INFO]: Synced Globe data
[19:33:24] [Render thread/WARN]: Unknown recipe category: oxidized:kiln_smelting/oxidized:smooth_basalt_smelting
[19:33:24] [Render thread/WARN]: Unknown recipe category: expandeddelight:juicing/expandeddelight:expandeddelight/juicing/sweet_berry_juice
[19:33:24] [Render thread/WARN]: Unknown recipe category: oxidized:kiln_smelting/oxidized:cracked_stone_bricks_smelting
[19:33:24] [Render thread/WARN]: Unknown recipe category: oxidized:kiln_smelting/oxidized:purple_glazed_terracotta_smelting
[19:33:24] [Render thread/WARN]: Unknown recipe category: oxidized:kiln_smelting/oxidized:smooth_red_sandstone_smelting
[19:33:24] [Render thread/WARN]: Unknown recipe category: oxidized:kiln_smelting/oxidized:brown_glazed_terracotta_smelting
[19:33:24] [Render thread/WARN]: Unknown recipe category: oxidized:kiln_smelting/oxidized:gray_glazed_terracotta_smelting
[19:33:24] [Render thread/WARN]: Unknown recipe category: oxidized:kiln_smelting/oxidized:pink_glazed_terracotta_smelting
[19:33:24] [Render thread/WARN]: Unknown recipe category: oxidized:kiln_smelting/oxidized:black_glazed_terracotta_smelting
[19:33:24] [Render thread/WARN]: Unknown recipe category: oxidized:kiln_smelting/oxidized:magenta_glazed_terracotta_smelting
[19:33:24] [Render thread/WARN]: Unknown recipe category: oxidized:kiln_smelting/oxidized:light_gray_glazed_terracotta_smelting
[19:33:24] [Render thread/WARN]: Unknown recipe category: oxidized:kiln_smelting/oxidized:white_glazed_terracotta_smelting
[19:33:24] [Render thread/WARN]: Unknown recipe category: oxidized:kiln_smelting/oxidized:nether_brick_smelting
[19:33:24] [Render thread/WARN]: Unknown recipe category: oxidized:kiln_smelting/oxidized:smooth_quartz_smelting
[19:33:24] [Render thread/WARN]: Unknown recipe category: oxidized:kiln_smelting/oxidized:blue_glazed_terracotta_smelting
[19:33:24] [Render thread/WARN]: Unknown recipe category: oxidized:kiln_smelting/oxidized:lime_glazed_terracotta_smelting
[19:33:24] [Render thread/WARN]: Unknown recipe category: oxidized:kiln_smelting/oxidized:yellow_glazed_terracotta_smelting
[19:33:24] [Render thread/WARN]: Unknown recipe category: oxidized:kiln_smelting/oxidized:cyan_glazed_terracotta_smelting
[19:33:24] [REI-ReloadPlugins/INFO]: [REI] Reloading Plugin Manager [REIPlugin] stage [START], registered 25 plugins: AdornReiServer of AdornReiServer [adorn], DefaultRuntimePlugin of DefaultRuntimePlugin [roughlyenoughitems], AdornReiClient of AdornReiClient [adorn], APPlugin of APPlugin [architects_palette], REIPlugin of REIPlugin [betterend], CharmReiClientPlugin of CharmReiClientPlugin [charm], DBServerPlugin of DBServerPlugin [decorative_blocks], DBClientPlugin of DBClientPlugin [decorative_blocks], ExpandedDelightREI of ExpandedDelightREI [expandeddelight], FarmersDelightModREI of FarmersDelightModREI [farmersdelight], REIIntegration of REIIntegration [ftblibrary], FTBQuestsREIIntegration of FTBQuestsREIIntegration [ftbquests], OwoReiPlugin of OwoReiPlugin [owo], OxidizedREIPlugin of OxidizedREIPlugin [oxidized], ClientPlugin of ClientPlugin [roughly_enough_trades], DefaultClientRuntimePlugin of DefaultClientRuntimePlugin [roughlyenoughitems], REPClientPlugin of REPClientPlugin [roughlyenoughprofessions], PluginEntry of PluginEntry [roughlyenoughresources], SpiritPlugin of SpiritPlugin [spirit], REICompat of REICompat [the_bumblezone], REIPlugin of REIPlugin [toms_storage], REICompat of REICompat [twilightforest], FabricFluidAPISupportPlugin, DefaultPlugin of DefaultPlugin [roughlyenoughitems], DefaultClientPlugin of DefaultClientPlugin [roughlyenoughitems]
[19:33:24] [Render thread/WARN]: Unknown recipe category: oxidized:kiln_smelting/oxidized:green_glazed_terracotta_smelting
[19:33:24] [Render thread/WARN]: Unknown recipe category: oxidized:kiln_smelting/oxidized:stone_kiln_smelting
[19:33:24] [Render thread/WARN]: Unknown recipe category: oxidized:kiln_smelting/oxidized:glass_kiln_smelting
[19:33:24] [Render thread/WARN]: Unknown recipe category: oxidized:kiln_smelting/oxidized:terracotta_kiln_smelting
[19:33:24] [Render thread/WARN]: Unknown recipe category: oxidized:kiln_smelting/oxidized:smooth_sandstone_smelting
[19:33:24] [Render thread/WARN]: Unknown recipe category: oxidized:kiln_smelting/oxidized:cracked_deepslate_tiles_smelting
[19:33:24] [Render thread/WARN]: Unknown recipe category: oxidized:kiln_smelting/oxidized:cracked_polished_blackstone_bricks_smelting
[19:33:24] [Render thread/WARN]: Unknown recipe category: expandeddelight:juicing/expandeddelight:expandeddelight/juicing/apple_juice
[19:33:24] [Render thread/WARN]: Unknown recipe category: expandeddelight:juicing/expandeddelight:expandeddelight/juicing/melon_juice
[19:33:24] [Render thread/WARN]: Unknown recipe category: oxidized:kiln_smelting/oxidized:red_glazed_terracotta_smelting
[19:33:24] [Render thread/WARN]: Unknown recipe category: oxidized:kiln_smelting/oxidized:deepslate_smelting
[19:33:24] [Render thread/WARN]: Unknown recipe category: oxidized:kiln_smelting/oxidized:cracked_nether_bricks_smelting
[19:33:24] [Render thread/WARN]: Unknown recipe category: oxidized:kiln_smelting/oxidized:orange_glazed_terracotta_smelting
[19:33:24] [Render thread/WARN]: Unknown recipe category: oxidized:kiln_smelting/oxidized:brick_kiln_smelting
[19:33:24] [Render thread/WARN]: Unknown recipe category: oxidized:kiln_smelting/oxidized:light_blue_glazed_terracotta_smelting
[19:33:24] [Render thread/WARN]: Unknown recipe category: oxidized:kiln_smelting/oxidized:charcoal_kiln_smelting
[19:33:24] [Render thread/WARN]: Unknown recipe category: oxidized:kiln_smelting/oxidized:cracked_deepslate_bricks_smelting
[19:33:24] [Render thread/WARN]: Unknown recipe category: expandeddelight:juicing/expandeddelight:expandeddelight/juicing/glow_berry_juice
[19:33:24] [Render thread/WARN]: Unknown recipe category: oxidized:kiln_smelting/oxidized:smooth_stone_kiln_smelting
[19:33:24] [REI-ReloadPlugins/INFO]: [REI] Reloading Plugin Manager [REIClientPlugin] stage [START], registered 20 plugins: AdornReiClient of AdornReiClient [adorn], APPlugin of APPlugin [architects_palette], REIPlugin of REIPlugin [betterend], CharmReiClientPlugin of CharmReiClientPlugin [charm], DBClientPlugin of DBClientPlugin [decorative_blocks], ExpandedDelightREI of ExpandedDelightREI [expandeddelight], FarmersDelightModREI of FarmersDelightModREI [farmersdelight], REIIntegration of REIIntegration [ftblibrary], FTBQuestsREIIntegration of FTBQuestsREIIntegration [ftbquests], OwoReiPlugin of OwoReiPlugin [owo], OxidizedREIPlugin of OxidizedREIPlugin [oxidized], ClientPlugin of ClientPlugin [roughly_enough_trades], DefaultClientRuntimePlugin of DefaultClientRuntimePlugin [roughlyenoughitems], REPClientPlugin of REPClientPlugin [roughlyenoughprofessions], PluginEntry of PluginEntry [roughlyenoughresources], SpiritPlugin of SpiritPlugin [spirit], REICompat of REICompat [the_bumblezone], REIPlugin of REIPlugin [toms_storage], REICompat of REICompat [twilightforest], DefaultClientPlugin of DefaultClientPlugin [roughlyenoughitems]
[19:33:25] [InventoryHUD+ version check/INFO]: [STDOUT]: [InventoryHUD+] Can't find update string
[19:33:27] [Render thread/INFO]: Loading all registered leaf blocks.
[19:33:27] [Worker-Main-2/WARN]: Ignoring unknown attribute 'forge:entity_gravity'
[19:33:27] [Worker-Main-2/WARN]: Ignoring unknown attribute 'forge:entity_gravity'
[19:33:27] [Worker-Main-7/WARN]: Ignoring unknown attribute 'forge:entity_gravity'
[19:33:27] [Worker-Main-7/WARN]: Ignoring unknown attribute 'forge:entity_gravity'
[19:33:27] [Worker-Main-7/WARN]: Ignoring unknown attribute 'forge:entity_gravity'
[19:33:28] [Render thread/INFO]: Animated skins loaded and ready to use!
[19:33:28] [Render thread/INFO]: Reloading entity icon resources...
[19:33:28] [Render thread/INFO]: Done!
[19:33:28] [Render thread/INFO]: Stopping worker threads
[19:33:28] [Render thread/INFO]: Started 6 worker threads
[19:33:29] [Render thread/INFO]: Loaded 137 advancements
[19:33:29] [Server thread/INFO]: Saving and pausing game...
[19:33:29] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:overworld
[19:33:29] [Server thread/INFO]: Saving grave backup data
[19:33:29] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/twilightforest:twilight_forest
[19:33:29] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/paradise_lost:paradise_lost
[19:33:29] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_end
[19:33:29] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_nether
[19:33:29] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/edenring:edenring
[19:33:29] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/the_bumblezone:the_bumblezone
[19:33:29] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/deeperdarker:otherside
[19:33:29] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/voidz:void
[19:33:31] [REI-ReloadPlugins/INFO]: [REI] Reloading Plugin Manager [REIServerPlugin] stage [START], registered 5 plugins: AdornReiServer of AdornReiServer [adorn], DefaultRuntimePlugin of DefaultRuntimePlugin [roughlyenoughitems], DBServerPlugin of DBServerPlugin [decorative_blocks], FabricFluidAPISupportPlugin, DefaultPlugin of DefaultPlugin [roughlyenoughitems]
[19:33:31] [REI-ReloadPlugins/INFO]: [REI] Reloaded Plugin Manager [REIPlugin] with 25 plugins in 81.67 ms.
[19:33:31] [REI-ReloadPlugins/INFO]: [REI] Reloaded Plugin Manager [REIClientPlugin] with 20 plugins in 7.217 s.
[19:33:31] [REI-ReloadPlugins/INFO]: [REI] Reloaded Plugin Manager [REIServerPlugin] with 5 plugins in 2.038 ms.
[19:33:31] [REI-ReloadPlugins/INFO]: [REI] Reloading Plugin Manager [REIPlugin] stage [END], registered 25 plugins: AdornReiServer of AdornReiServer [adorn], DefaultRuntimePlugin of DefaultRuntimePlugin [roughlyenoughitems], AdornReiClient of AdornReiClient [adorn], APPlugin of APPlugin [architects_palette], REIPlugin of REIPlugin [betterend], CharmReiClientPlugin of CharmReiClientPlugin [charm], DBServerPlugin of DBServerPlugin [decorative_blocks], DBClientPlugin of DBClientPlugin [decorative_blocks], ExpandedDelightREI of ExpandedDelightREI [expandeddelight], FarmersDelightModREI of FarmersDelightModREI [farmersdelight], REIIntegration of REIIntegration [ftblibrary], FTBQuestsREIIntegration of FTBQuestsREIIntegration [ftbquests], OwoReiPlugin of OwoReiPlugin [owo], OxidizedREIPlugin of OxidizedREIPlugin [oxidized], ClientPlugin of ClientPlugin [roughly_enough_trades], DefaultClientRuntimePlugin of DefaultClientRuntimePlugin [roughlyenoughitems], REPClientPlugin of REPClientPlugin [roughlyenoughprofessions], PluginEntry of PluginEntry [roughlyenoughresources], SpiritPlugin of SpiritPlugin [spirit], REICompat of REICompat [the_bumblezone], REIPlugin of REIPlugin [toms_storage], REICompat of REICompat [twilightforest], FabricFluidAPISupportPlugin, DefaultPlugin of DefaultPlugin [roughlyenoughitems], DefaultClientPlugin of DefaultClientPlugin [roughlyenoughitems]
[19:33:31] [REI-ReloadPlugins/INFO]: [REI] Reloading Plugin Manager [REIClientPlugin] stage [END], registered 20 plugins: AdornReiClient of AdornReiClient [adorn], APPlugin of APPlugin [architects_palette], REIPlugin of REIPlugin [betterend], CharmReiClientPlugin of CharmReiClientPlugin [charm], DBClientPlugin of DBClientPlugin [decorative_blocks], ExpandedDelightREI of ExpandedDelightREI [expandeddelight], FarmersDelightModREI of FarmersDelightModREI [farmersdelight], REIIntegration of REIIntegration [ftblibrary], FTBQuestsREIIntegration of FTBQuestsREIIntegration [ftbquests], OwoReiPlugin of OwoReiPlugin [owo], OxidizedREIPlugin of OxidizedREIPlugin [oxidized], ClientPlugin of ClientPlugin [roughly_enough_trades], DefaultClientRuntimePlugin of DefaultClientRuntimePlugin [roughlyenoughitems], REPClientPlugin of REPClientPlugin [roughlyenoughprofessions], PluginEntry of PluginEntry [roughlyenoughresources], SpiritPlugin of SpiritPlugin [spirit], REICompat of REICompat [the_bumblezone], REIPlugin of REIPlugin [toms_storage], REICompat of REICompat [twilightforest], DefaultClientPlugin of DefaultClientPlugin [roughlyenoughitems]
[19:33:31] [REI-ReloadPlugins/ERROR]: [REI] REICompat of REICompat [twilightforest] plugin failed to reloadable-plugin/DisplayRegistryImpl/!
java.lang.UnsupportedOperationException: null
	at java.util.ImmutableCollections.uoe(ImmutableCollections.java:142) ~[?:?]
	at java.util.ImmutableCollections$AbstractImmutableCollection.removeIf(ImmutableCollections.java:152) ~[?:?]
	at twilightforest.compat.rei.REICompat.registerDisplays(REICompat.java:65) ~[twilightforest-fabric-1.19.2-4.2.301.jar:?]
	at me.shedaniel.rei.impl.client.registry.display.DisplayRegistryImpl.acceptPlugin(DisplayRegistryImpl.java:181) ~[RoughlyEnoughItems-9.1.562.jar:?]
	at me.shedaniel.rei.impl.client.registry.display.DisplayRegistryImpl.acceptPlugin(DisplayRegistryImpl.java:58) ~[RoughlyEnoughItems-9.1.562.jar:?]
	at me.shedaniel.rei.api.common.registry.Reloadable.acceptPlugin(Reloadable.java:72) ~[RoughlyEnoughItems-9.1.562.jar:?]
	at me.shedaniel.rei.impl.common.plugins.PluginManagerImpl.lambda$startReload$9(PluginManagerImpl.java:340) ~[RoughlyEnoughItems-9.1.562.jar:?]
	at me.shedaniel.rei.impl.common.plugins.PluginManagerImpl.lambda$pluginSection$4(PluginManagerImpl.java:198) ~[RoughlyEnoughItems-9.1.562.jar:?]
	at me.shedaniel.rei.impl.common.plugins.PluginManagerImpl.lambda$startReload$10(PluginManagerImpl.java:330) ~[RoughlyEnoughItems-9.1.562.jar:?]
	at me.shedaniel.rei.impl.common.plugins.PluginManagerImpl.pluginSection(PluginManagerImpl.java:196) ~[RoughlyEnoughItems-9.1.562.jar:?]
	at me.shedaniel.rei.impl.common.plugins.PluginManagerImpl.startReload(PluginManagerImpl.java:328) ~[RoughlyEnoughItems-9.1.562.jar:?]
	at me.shedaniel.rei.RoughlyEnoughItemsCore._reloadPlugins(RoughlyEnoughItemsCore.java:123) ~[RoughlyEnoughItems-9.1.562.jar:?]
	at me.shedaniel.rei.RoughlyEnoughItemsCoreClient.lambda$reloadPlugins$24(RoughlyEnoughItemsCoreClient.java:467) ~[RoughlyEnoughItems-9.1.562.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) [?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[19:33:33] [Worker-Main-7/WARN]: Ignoring unknown attribute 'forge:entity_gravity'
[19:33:33] [Worker-Main-7/WARN]: Ignoring unknown attribute 'forge:entity_gravity'
[19:33:33] [REI-ReloadPlugins/INFO]: [REI] Reloading Plugin Manager [REIServerPlugin] stage [END], registered 5 plugins: AdornReiServer of AdornReiServer [adorn], DefaultRuntimePlugin of DefaultRuntimePlugin [roughlyenoughitems], DBServerPlugin of DBServerPlugin [decorative_blocks], FabricFluidAPISupportPlugin, DefaultPlugin of DefaultPlugin [roughlyenoughitems]
[19:33:33] [REI-ReloadPlugins/INFO]: [REI] Reloaded Plugin Manager [REIPlugin] with 25 plugins in 61.04 ms.
[19:33:33] [REI-ReloadPlugins/INFO]: [REI] Reloaded Plugin Manager [REIClientPlugin] with 20 plugins in 1.511 s.
[19:33:33] [REI-ReloadPlugins/INFO]: [REI] Reloaded Plugin Manager [REIServerPlugin] with 5 plugins in 9.572 ms.
[19:33:36] [Worker-Main-11/WARN]: Ignoring unknown attribute 'forge:entity_gravity'
[19:33:36] [Worker-Main-11/WARN]: Ignoring unknown attribute 'forge:entity_gravity'
[19:33:36] [Worker-Main-11/WARN]: Ignoring unknown attribute 'forge:entity_gravity'
[19:33:36] [Worker-Main-11/WARN]: Ignoring unknown attribute 'forge:entity_gravity'
[19:33:36] [Worker-Main-11/WARN]: Ignoring unknown attribute 'forge:entity_gravity'
[19:33:36] [Worker-Main-11/WARN]: Ignoring unknown attribute 'forge:entity_gravity'
[19:33:36] [Worker-Main-11/WARN]: Ignoring unknown attribute 'forge:entity_gravity'
[19:33:36] [Worker-Main-11/WARN]: Ignoring unknown attribute 'forge:entity_gravity'
[19:33:36] [Worker-Main-11/WARN]: Ignoring unknown attribute 'forge:entity_gravity'
[19:33:36] [Worker-Main-11/WARN]: Ignoring unknown attribute 'forge:entity_gravity'
[19:33:36] [Worker-Main-10/WARN]: Ignoring unknown attribute 'forge:entity_gravity'
[19:33:36] [Worker-Main-10/WARN]: Ignoring unknown attribute 'forge:entity_gravity'
[19:33:36] [Worker-Main-10/WARN]: Ignoring unknown attribute 'forge:entity_gravity'
[19:33:36] [Worker-Main-10/WARN]: Ignoring unknown attribute 'forge:entity_gravity'
[19:33:36] [Worker-Main-10/WARN]: Ignoring unknown attribute 'forge:entity_gravity'
[19:33:36] [Worker-Main-10/WARN]: Ignoring unknown attribute 'forge:entity_gravity'
[19:33:36] [Worker-Main-10/WARN]: Ignoring unknown attribute 'forge:entity_gravity'
[19:33:36] [Worker-Main-10/WARN]: Ignoring unknown attribute 'forge:entity_gravity'
[19:33:36] [Worker-Main-10/WARN]: Ignoring unknown attribute 'forge:entity_gravity'
[19:33:36] [Worker-Main-10/WARN]: Ignoring unknown attribute 'forge:entity_gravity'
[19:33:36] [Worker-Main-10/WARN]: Ignoring unknown attribute 'forge:entity_gravity'
[19:33:36] [Worker-Main-10/WARN]: Ignoring unknown attribute 'forge:entity_gravity'
[19:33:38] [Worker-Main-3/ERROR]: Hanging entity at invalid position: class_2338{x=255, y=8, z=2}
[19:33:38] [Worker-Main-3/ERROR]: Hanging entity at invalid position: class_2338{x=255, y=7, z=0}
[19:33:38] [Worker-Main-3/ERROR]: Hanging entity at invalid position: class_2338{x=257, y=6, z=2}
[19:33:38] [Worker-Main-3/ERROR]: Hanging entity at invalid position: class_2338{x=256, y=6, z=0}
[19:33:44] [Worker-Main-4/WARN]: Ignoring unknown attribute 'forge:entity_gravity'
[19:33:44] [Worker-Main-4/WARN]: Ignoring unknown attribute 'forge:entity_gravity'
[19:33:44] [Worker-Main-4/WARN]: Ignoring unknown attribute 'forge:entity_gravity'
[19:33:44] [Worker-Main-4/WARN]: Ignoring unknown attribute 'forge:entity_gravity'
[19:33:44] [Worker-Main-4/WARN]: Ignoring unknown attribute 'forge:entity_gravity'
[19:33:44] [Worker-Main-4/WARN]: Ignoring unknown attribute 'forge:entity_gravity'
[19:33:44] [Worker-Main-4/WARN]: Ignoring unknown attribute 'forge:entity_gravity'
[19:33:44] [Worker-Main-4/WARN]: Ignoring unknown attribute 'forge:entity_gravity'
[19:33:44] [Worker-Main-4/WARN]: Ignoring unknown attribute 'forge:entity_gravity'
[19:33:44] [Worker-Main-4/WARN]: Ignoring unknown attribute 'forge:entity_gravity'
[19:33:44] [Worker-Main-4/WARN]: Ignoring unknown attribute 'forge:entity_gravity'
[19:33:44] [Worker-Main-4/WARN]: Ignoring unknown attribute 'forge:entity_gravity'
[19:33:44] [Worker-Main-4/WARN]: Ignoring unknown attribute 'forge:entity_gravity'
[19:33:44] [Worker-Main-3/WARN]: Ignoring unknown attribute 'forge:entity_gravity'
[19:33:44] [Worker-Main-3/WARN]: Ignoring unknown attribute 'forge:entity_gravity'
[19:33:44] [Worker-Main-3/WARN]: Ignoring unknown attribute 'forge:entity_gravity'
[19:33:44] [Worker-Main-3/WARN]: Ignoring unknown attribute 'forge:entity_gravity'
[19:33:44] [Worker-Main-3/WARN]: Ignoring unknown attribute 'forge:entity_gravity'
[19:33:44] [Worker-Main-3/WARN]: Ignoring unknown attribute 'forge:entity_gravity'
[19:33:44] [Worker-Main-3/WARN]: Ignoring unknown attribute 'forge:entity_gravity'
[19:33:44] [Worker-Main-3/WARN]: Ignoring unknown attribute 'forge:entity_gravity'
[19:33:44] [Worker-Main-3/WARN]: Ignoring unknown attribute 'forge:entity_gravity'
[19:33:44] [Worker-Main-3/WARN]: Ignoring unknown attribute 'forge:entity_gravity'
[19:33:44] [Worker-Main-3/WARN]: Ignoring unknown attribute 'forge:entity_gravity'
[19:33:44] [Worker-Main-3/WARN]: Ignoring unknown attribute 'forge:entity_gravity'
[19:33:44] [Worker-Main-4/WARN]: Ignoring unknown attribute 'forge:entity_gravity'
[19:33:44] [Worker-Main-4/WARN]: Ignoring unknown attribute 'forge:entity_gravity'
[19:33:44] [Worker-Main-4/WARN]: Ignoring unknown attribute 'forge:entity_gravity'
[19:33:44] [Worker-Main-4/WARN]: Ignoring unknown attribute 'forge:entity_gravity'
[19:33:44] [Worker-Main-4/WARN]: Ignoring unknown attribute 'forge:entity_gravity'
[19:33:44] [Worker-Main-4/WARN]: Ignoring unknown attribute 'forge:entity_gravity'
[19:33:44] [Worker-Main-4/WARN]: Ignoring unknown attribute 'forge:entity_gravity'
[19:33:44] [Worker-Main-4/WARN]: Ignoring unknown attribute 'forge:entity_gravity'
[19:33:46] [Worker-Main-1/ERROR]: Hanging entity at invalid position: class_2338{x=255, y=7, z=-17}
[19:33:46] [Worker-Main-1/ERROR]: Hanging entity at invalid position: class_2338{x=255, y=6, z=-16}
[19:33:46] [Worker-Main-1/ERROR]: Hanging entity at invalid position: class_2338{x=256, y=7, z=-18}
[19:33:48] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 2152ms or 43 ticks behind
[19:33:49] [Server thread/INFO]: oofmas has made the advancement [I've been falling, for 30 minutes!]
[19:33:49] [Render thread/INFO]: [CHAT] oofmas has made the advancement [I've been falling, for 30 minutes!]
[19:33:49] [Render thread/INFO]: Loaded 165 advancements
[19:33:52] [Server thread/INFO]: [oofmas: Summoned new Anezka Dzialo]
[19:33:52] [Server thread/INFO]: [oofmas: Summoned new Faulco Oshinsky]
[19:33:52] [Render thread/INFO]: [CHAT] Summoned new Anezka Dzialo
[19:33:52] [Server thread/INFO]: [oofmas: Summoned new Salali Boring]
[19:33:52] [Render thread/INFO]: [CHAT] Summoned new Faulco Oshinsky
[19:33:52] [Render thread/INFO]: [CHAT] Summoned new Salali Boring
[19:34:01] [Render thread/WARN]: Reclaimed 25360 bytes at address 2187865555008 that were leaked from an unknown location (logging is disabled)
[19:34:01] [Render thread/WARN]: Reclaimed 3804 bytes at address 2187036393472 that were leaked from an unknown location (logging is disabled)
[19:34:01] [Render thread/WARN]: Reclaimed 3348 bytes at address 2187075456512 that were leaked from an unknown location (logging is disabled)
[19:34:01] [Render thread/WARN]: Reclaimed 22320 bytes at address 2187834754752 that were leaked from an unknown location (logging is disabled)
[19:34:01] [Render thread/WARN]: Reclaimed 197280 bytes at address 2187957436992 that were leaked from an unknown location (logging is disabled)
[19:34:01] [Render thread/WARN]: Reclaimed 29592 bytes at address 2187206263872 that were leaked from an unknown location (logging is disabled)
[19:34:02] [Server thread/INFO]: Saving and pausing game...
[19:34:02] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:overworld
[19:34:02] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/twilightforest:twilight_forest
[19:34:02] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/paradise_lost:paradise_lost
[19:34:02] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_end
[19:34:02] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_nether
[19:34:02] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/edenring:edenring
[19:34:02] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/the_bumblezone:the_bumblezone
[19:34:02] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/deeperdarker:otherside
[19:34:02] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/voidz:void
[19:34:03] [Render thread/INFO]: Stopping!
```

### Other mods

https://www.modpackindex.com/modpack/28903/better-mc-fabric-1192

### Additional Information

This issue only started happening in the latest version of our Fabric modpacks when we added Paradise Lost.

This issue is widespread across all users.

This issue is also present in one of our larger modpacks. https://www.curseforge.com/minecraft/modpacks/medieval-mc-fabric

**Comment by danif86** [comment]
Removing only Paradise Lost mob atleast fixes it (tested several times)

**Comment by lamoyrl90** [comment]
Can confirm using 0.2.0 beta 1.19

**Comment by danif86** [comment]
Progress`?

**Comment by TheGag96** [comment]
I've been experiencing this also.
