### ISSUE TITLE
Crash: with create upon launch

### ISSUE THREAD

**Issue by OrdinaryCloverOC** [devs-immortal/The-Aether#731]
### What were you doing when the crash occured? How can we replicate it?

launch game with create

### Did it crash the client or server?

Client

### Mod Version

Beta 2.0

### Fabric API Version

0.66.0 1.19.2

### Crash Report

```Shell
---- Minecraft Crash Report ----
// There are four lights!
Time: 2022-11-19 21:16:34
Description: Initializing game
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'paradise_lost'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:459)
	at net.minecraft.client.main.Main.method_44604(Main.java:205)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.prismlauncher.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
	at org.prismlauncher.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:176)
	at org.prismlauncher.impl.OneSixLauncher.launch(OneSixLauncher.java:186)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:144)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:74)
Caused by: java.lang.ExceptionInInitializerError
	at net.id.paradiselost.util.RenderUtils.auralCutoutMippedRenderLayer(RenderUtils.java:56)
	at net.id.paradiselost.blocks.ParadiseLostBlockActions.lambda$static$7(ParadiseLostBlockActions.java:32)
	at net.id.incubus_core.util.RegistryQueue.register(RegistryQueue.java:111)
	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:721)
	at net.id.incubus_core.util.RegistryQueue.register(RegistryQueue.java:104)
	at net.id.paradiselost.blocks.ParadiseLostBlocks.init(ParadiseLostBlocks.java:447)
	at net.id.paradiselost.ParadiseLost.onInitialize(ParadiseLost.java:86)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 17 more
Caused by: java.lang.IllegalStateException: RenderLayer RenderType[solid_paradise_lost:aural_1705771796:CompositeState[[texture[Optional[minecraft:textures/atlas/blocks.png](blur=false, mipmap=true)], shader[Optional[ladysnake.satin.impl.ResettableManagedCoreShader$$Lambda$6406/0x000000080193f808@46ff896a]], no_transparency, depth_test[<=], cull[true], lightmap[true], overlay[false], no_layering, main_target, default_texturing, write_mask_state[writeColor=true, writeDepth=true], line_width[1.0]], outlineProperty=affects_outline]] was added too late.
	at ladysnake.satin.impl.BlockRenderLayerRegistry.registerRenderLayer(BlockRenderLayerRegistry.java:34)
	at ladysnake.satin.api.util.RenderLayerHelper.registerBlockRenderLayer(RenderLayerHelper.java:90)
	at net.id.paradiselost.client.rendering.shader.ParadiseLostRenderLayers.<clinit>(ParadiseLostRenderLayers.java:26)
	... 25 more
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------
-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:459)
-- Initialization --
Details:
	Modules: 
Stacktrace:
	at net.minecraft.client.main.Main.method_44604(Main.java:205)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.prismlauncher.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
	at org.prismlauncher.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:176)
	at org.prismlauncher.impl.OneSixLauncher.launch(OneSixLauncher.java:186)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:144)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:74)
```

### Other mods

https://modrinth.com/mod/create-fabric/version/1.19.2-0.5.0f-776
along with trinkets 3.4.0, and fabric api

### Additional Information

prism launcher

**Comment by OrdinaryCloverOC** [comment]
it works with the better mc modpack, but not with these mods alone...

**Comment by TropheusJ** [comment]
will be fixed in next Create release
