### ISSUE TITLE
Crash: exit code 255

### ISSUE THREAD

**Issue by molnarnoah** [devs-immortal/The-Aether#746]
### What were you doing when the crash occured? How can we replicate it?

Hello! After I installed Create mod for my 1.19.2 minecraft it exits with code 255. If i remote Create it works. Can you help?

### Did it crash the client or server?

Client

### Mod Version

Beta 2.0.2

### Fabric API Version

14.10

### Crash Report

```Shell
Hello! After I installed Create mod for my 1.19.2 minecraft it exits with code 255. If i remote Create it works. Can you help?

---- Minecraft Crash Report ----
// My bad.

Time: 2022-12-12 17:42:06
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'paradise_lost'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:459)
	at net.minecraft.client.main.Main.method_44604(Main.java:205)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.ExceptionInInitializerError
	at net.id.paradiselost.util.RenderUtils.auralCutoutMippedRenderLayer(RenderUtils.java:56)
	at net.id.paradiselost.blocks.ParadiseLostBlockActions.lambda$static$7(ParadiseLostBlockActions.java:32)
	at net.id.incubus_core.util.RegistryQueue.register(RegistryQueue.java:111)
	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:721)
	at net.id.incubus_core.util.RegistryQueue.register(RegistryQueue.java:104)
	at net.id.paradiselost.blocks.ParadiseLostBlocks.init(ParadiseLostBlocks.java:450)
	at net.id.paradiselost.ParadiseLost.onInitialize(ParadiseLost.java:86)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 8 more
Caused by: java.lang.IllegalStateException: RenderLayer RenderType[solid_paradise_lost:aural_1964445554:CompositeState[[texture[Optional[minecraft:textures/atlas/blocks.png](blur=false, mipmap=true)], shader[Optional[ladysnake.satin.impl.ResettableManagedCoreShader$$Lambda$7444/0x0000000801030d10@34c7fa15]], no_transparency, depth_test[<=], cull[true], lightmap[true], overlay[false], no_layering, main_target, default_texturing, write_mask_state[writeColor=true, writeDepth=true], line_width[1.0]], outlineProperty=affects_outline]] was added too late.
	at ladysnake.satin.impl.BlockRenderLayerRegistry.registerRenderLayer(BlockRenderLayerRegistry.java:34)
	at ladysnake.satin.api.util.RenderLayerHelper.registerBlockRenderLayer(RenderLayerHelper.java:90)
	at net.id.paradiselost.client.rendering.shader.ParadiseLostRenderLayers.<clinit>(ParadiseLostRenderLayers.java:26)
	... 16 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:459)

-- Initialization --
Details:
	Modules: 
Stacktrace:
	at net.minecraft.client.main.Main.method_44604(Main.java:205)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Mac OS X (x86_64) version 12.1
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 904795528 bytes (862 MiB) / 2013265920 bytes (1920 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
	Identifier: Intel64 Family 6 Model 142 Stepping 10
	Microarchitecture: unknown
	Frequency (GHz): 1.40
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: Intel Iris Plus Graphics 645
	Graphics card #0 vendor: Intel
	Graphics card #0 VRAM (MB): 1536.00
	Graphics card #0 deviceId: 0x3ea6
	Graphics card #0 versionInfo: Revision ID: 0x0001
	Memory slot #0 capacity (MB): 4096.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: LPDDR3
	Memory slot #1 capacity (MB): 4096.00
	Memory slot #1 clockSpeed (GHz): 2.13
	Memory slot #1 type: LPDDR3
	Virtual memory max (MB): 9216.00
	Virtual memory used (MB): 5874.60
	Swap memory total (MB): 1024.00
	Swap memory used (MB): 539.50
	JVM Flags: 8 total; -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		adorn: Adorn 3.6.1+1.19
		create: Create 0.5.0g-796+1.19.2
			com_google_code_findbugs_jsr305: jsr305 3.0.2
			fake-player-api: Fake Player API 0.5.0
			flywheel: Flywheel 0.6.8-1
			forgeconfigapiport: Forge Config API Port 4.2.6
				com_electronwill_night-config_core: core 3.6.5
				com_electronwill_night-config_toml: toml 3.6.5
			milk: Milk Lib 1.0.51
				dripstone_fluid_lib: Dripstone Fluid Lib 2.0.1
			noindium: No Indium? 1.1.0+1.19
			porting_lib: Porting Lib 2.1.623+1.19.2
				forge_tags: Porting Lib Tags 3.0
				porting_lib_base: Porting Lib Base 2.1.623+1.19.2
					com_github_llamalad7_mixinextras: MixinExtras 0.1.1
					mm: Manningham Mills 2.3
					serialization_hooks: Serialization Hooks 0.3.26
				porting_lib_entity: Porting Lib Entity 2.1.623+1.19.2
				porting_lib_lazy_registration: Porting Lib Lazy Register 2.1.623+1.19.2
				porting_lib_model_generators: Porting Lib Model Generators 2.1.623+1.19.2
				porting_lib_models: Porting Lib Models 2.1.623+1.19.2
				porting_lib_networking: Porting Lib Networking 2.1.623+1.19.2
				porting_lib_obj_loader: Porting Lib Obj Loader 2.1.623+1.19.2
					porting_lib_model_loader: Porting Lib Model Loader 2.1.623+1.19.2
				porting_lib_transfer: Porting Lib Transfer 2.1.623+1.19.2
					porting_lib_extensions: Porting Lib Extensions 2.1.623+1.19.2
						porting_lib_accessors: Porting Lib Accessors 2.1.623+1.19.2
						porting_lib_attributes: Porting Lib Attributes 2.1.623+1.19.2
							porting_lib_constants: Porting Lib Constants 2.1.623+1.19.2
						porting_lib_common: Porting Lib Common 2.1.623+1.19.2
			reach-entity-attributes: Reach Entity Attributes 2.3.0
			registrate-fabric: Registrate for Fabric 1.1.44-MC1.19.2
		createaddition: Create Crafts & Additions ${version}
			team_reborn_energy: Energy 2.2.0
		dimdoors: DimensionalDoors 5.0.0
			cardinal-components-chunk: Cardinal Components API (chunks) 5.0.0-beta.1
			cardinal-components-item: Cardinal Components API (items) 5.0.0-beta.1
			cardinal-components-level: Cardinal Components API (world saves) 5.0.0-beta.1
			cardinal-components-world: Cardinal Components API (worlds) 5.0.0-beta.1
			com_flowpowered_flow-math: flow-math 1.0.3
			com_github_dimensionaldevelopment_poly2tri_java: poly2tri.java 0.1.1
			matrix: Matrix 1.0.0
			org_jgrapht_jgrapht-core: jgrapht-core 1.1.0
		dramaticdoors: Dramatic Doors (Fabric) 1.19.2-1.3.5_1
		fabric-api: Fabric API 0.69.0+1.19.2
			fabric-api-base: Fabric API Base 0.4.13+0d0f210290
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.12+93d8cb8290
			fabric-biome-api-v1: Fabric Biome API (v1) 9.0.20+0d0f210290
			fabric-block-api-v1: Fabric Block API (v1) 1.0.1+12bfe4ea90
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.22+c6af733c90
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.3+b35fea8390
			fabric-command-api-v1: Fabric Command API (v1) 1.2.13+f71b366f90
			fabric-command-api-v2: Fabric Command API (v2) 2.1.9+93d8cb8290
			fabric-commands-v0: Fabric Commands (v0) 0.2.30+df3654b390
			fabric-containers-v0: Fabric Containers (v0) 0.1.38+df3654b390
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.4.4+6064db2a90
			fabric-convention-tags-v1: Fabric Convention Tags 1.2.0+27265b3490
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.7+aeb40ebe90
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.3.3+ad31814d90
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.33+0d0f210290
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.2+9244241690
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.31+6eb9a2a190
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.31+df3654b390
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.23+c6af733c90
			fabric-item-api-v1: Fabric Item API (v1) 1.6.1+fa140d5990
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.36+9244241690
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.23+aaaf9d3390
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.21+df3654b390
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.2+9244241690
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.10+83a8659290
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.13+9e7660c690
			fabric-message-api-v1: Fabric Message API (v1) 5.0.5+93d8cb8290
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.21+33fbc73890
			fabric-models-v0: Fabric Models (v0) 0.3.19+c6af733c90
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.8+3b1d070f90
			fabric-networking-v0: Fabric Networking (v0) 0.3.25+df3654b390
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.1.3+06e0e25190
			fabric-particles-v1: Fabric Particles (v1) 1.0.12+79adfe0a90
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.29+9244241690
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.1.0+e7aeff4590
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.17+aeb40ebe90
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.22+df3654b390
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.17+0d0f210290
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.9+c6af733c90
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.25+df3654b390
			fabric-rendering-v1: Fabric Rendering (v1) 1.11.1+73145abb90
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.1.1+aae9039d90
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.8.2+574a764890
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.30+b0bc9a6790
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.4+1cc24b1b90
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.1+c4f28df590
			fabric-textures-v0: Fabric Textures (v0) 1.0.22+aeb40ebe90
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.3+9d081d6490
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.3.2+42d99c3290
		fabric-language-kotlin: Fabric Language Kotlin 1.8.3+kotlin.1.7.10
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.7.10
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.7.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.7.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.7.10
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.18.3
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.4.0
		fabricloader: Fabric Loader 0.14.10
		immersive_portals: Immersive Portals 2.2.3
			cloth-config: Cloth Config v8 8.0.75
				cloth-basic-math: cloth-basic-math 0.6.1
			imm_ptl_core: Immersive Portals Core 2.2.3
			q_misc_util: QMiscUtil 2.2.3
		java: OpenJDK 64-Bit Server VM 17
		jei: Just Enough Items 11.3.0.262
		minecraft: Minecraft 1.19.2
		naturescompass: Nature's Compass 1.19.2-2.0.4-fabric
		paradise_lost: Paradise Lost 2.0.2-beta+1.19.2
			cardinal-components-base: Cardinal Components API (base) 5.0.1
			cardinal-components-entity: Cardinal Components API (entities) 5.0.1
			customportalapi: Custom Portal Api 0.0.1-beta54-1.19
			gud_recipe_confidence: Recipe Confidence 1.0.2
			incubus_core: Incubus Core 1.8.0
			satin: Satin 1.8.0
			trinkets: Trinkets 3.4.0
		travelerstitles: Traveler's Titles 1.19.2-Fabric-3.1.0
		yungsapi: YUNG's API 1.19.2-Fabric-3.8.2
			org_javassist_javassist: javassist 3.28.0-GA
			org_reflections_reflections: reflections 0.10.2
	Flywheel Backend: Uninitialized
	Launched Version: fabric-loader-0.14.10-1.19.2
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: Unknown
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: <unknown>
```

### Other mods

Create 
Dimensional Doors

**Comment by MBatt1** [comment]
This very likely comes down to a shader issue conflict caused by having create installed. To my knowledge I don't believe the issue is something we can resolve. Sorry!

**Comment by MBatt1** [comment]
@molnarnoah I think the latest version of PL (2.1.0) may work, if you'd like to try it and report if it still crashes or not
