### ISSUE TITLE
Crash: 

### ISSUE THREAD

**Issue by Izen9** [devs-immortal/The-Aether#762]
### What were you doing when the crash occured? How can we replicate it?

I opened a map in the paradise dimension, and upon selecting the map in the hotbar, the game crashed. When rejoining the server, it just keeps crashing

### Did it crash the client or server?

Client

### Mod Version

Beta 2.0.2

### Fabric API Version

0.69.0

### Crash Report

```Shell
java.lang.NullPointerException: Cannot read field "field_16021" because "material" is null
	at net.id.paradiselost.util.ParadiseLostMapColorUtil.getColor(ParadiseLostMapColorUtil.java:9)
	at net.minecraft.class_330$class_331.handler$dek000$updateTexture(class_330.java:1549)
	at net.minecraft.class_330$class_331.method_1776(class_330.java)
	at net.minecraft.class_330$class_331.method_1777(class_330.java:103)
	at net.minecraft.class_330.method_1773(class_330.java:40)
	at net.minecraft.class_759.method_3223(class_759.java:272)
	at net.minecraft.class_759.method_3231(class_759.java:247)
	at net.minecraft.class_759.method_3228(class_759.java:452)
	at net.minecraft.class_759.method_22976(class_759.java:364)
	at net.minecraft.class_757.method_3172(class_757.java:752)
	at net.minecraft.class_757.method_3188(class_757.java:1065)
	at net.minecraft.class_757.method_3192(class_757.java:816)
	at net.minecraft.class_310.method_1523(class_310.java:1177)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

**Comment by MBatt1** [comment]
Can you attempt this is Beta 2.1.0 and see if it still occurs? I'm unable to reproduce a crash.
