### ISSUE TITLE
Crash: Incompatibility with Medieval Items [1.20.1 and probably 1.20]

### ISSUE THREAD

**Issue by TheShadyyOneYT** [devs-immortal/The-Aether#805]
### What were you doing when the crash occured? How can we replicate it?

1. First, Download medieval weapons mod, latest version for game version 1.20.1
2. Next, download the new beta for fabric 1.20.1 of paradise
3. Launch the game and Finally, game crashes specifying: https://pastebin.com/fasiFv1G

Versions:
Medieval Weapons: 1.4.8
Paradise Lost: beta 2.2.1
Fabric Modloader: 0.16.2
Fabric API: 0.92.2
Game Version: 1.20.1

### Did it crash the client or server?

Client

### Mod Version

Beta 2.2.1

### Fabric API Version

0.92.2

### Crash Report

```Shell
https://pastebin.com/fasiFv1G
```

### Other mods

Medieval weapons is the cause of it currently: https://www.curseforge.com/minecraft/mc-mods/medievalweapons/files/4819203

Modlist: 
![Screenshot 2024-08-18 231943](https://github.com/user-attachments/assets/0e45ae88-7065-41cd-8d0f-866c03faf448)
![Screenshot 2024-08-18 231958](https://github.com/user-attachments/assets/df707074-a18f-4fde-bd9d-caf22ff43016)
![Screenshot 2024-08-18 232013](https://github.com/user-attachments/assets/d85c6f90-2149-487a-93e2-efbc78f17a15)
![Screenshot 2024-08-18 232020](https://github.com/user-attachments/assets/a979c4da-53e3-4a1e-8d3c-676f7926d241)

### Additional Information

Not really, just a small incompatibility I think or something that could be resolved. I have no idea honestly, I hardly understand code other than the fact I could determine which mod was the issue.

### **But here in the crash report this is where It occured I believe on my limited knowledge:**
`	Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NullPointerException [in thread "Render thread"]
		at net.minecraft.class_1831.<init>(class_1831.java:7)
		at net.minecraft.class_1766.<init>(class_1766.java:24)
		at net.minecraft.class_1821.<init>(class_1821.java:35)
		at net.id.paradiselost.items.ParadiseLostItems.<clinit>(ParadiseLostItems.java:87)
		at net.id.paradiselost.items.tools.ParadiseLostToolMaterials.<clinit>(ParadiseLostToolMaterials.java:11)
		at net.medievalweapons.compat.CompatItems.loadItems(CompatItems.java:232)
		at net.medievalweapons.init.ItemInit.init(ItemInit.java:141)
		at net.medievalweapons.MedievalMain.onInitialize(MedievalMain.java:22)
		... 7 more
Caused by: java.lang.ExceptionInInitializerError
	at net.id.paradiselost.items.tools.ParadiseLostToolMaterials.<clinit>(ParadiseLostToolMaterials.java:11)
	at net.medievalweapons.compat.CompatItems.loadItems(CompatItems.java:232)
	at net.medievalweapons.init.ItemInit.init(ItemInit.java:141)
	at net.medievalweapons.MedievalMain.onInitialize(MedievalMain.java:22)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399)
	... 6 more
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1832.method_8025()" because "$$0" is null
	at net.minecraft.class_1831.<init>(class_1831.java:7)
	at net.minecraft.class_1766.<init>(class_1766.java:24)
	at net.minecraft.class_1821.<init>(class_1821.java:35)
	at net.id.paradiselost.items.ParadiseLostItems.<clinit>(ParadiseLostItems.java:87)`

**Comment by MBatt1** [comment]
Yeah this might be an issue with the 'efficient' way that tool materials are being added by PL, I will work on a fix for 1.20 and check lower the 1.19 version as well

**Comment by MBatt1** [comment]
Doesn't appear to be a problem for 1.19.x or 1.20.0 but 1.20.1 is crashing

**Comment by PixelatedBruh** [comment]
I have a personal fork of medieval weapons that i have been slowly adding compatibility for mythic metals and ran into this issue when testing. after about idk 15 mins of messing with it I couldn't get it to work on my side.

**Comment by TheShadyyOneYT** [comment]
> I have a personal fork of medieval weapons that i have been slowly adding compatibility for mythic metals and ran into this issue when testing. after about idk 15 mins of messing with it I couldn't get it to work on my side.

the only thing that worked for me temporarily is to downgrade medieval weapons to 3.4.7 and wait for a fix in the mean time till 3.4.8 is fixed.

**Comment by MBatt1** [comment]
![image](https://github.com/user-attachments/assets/c18e74e5-abb9-4ae9-9884-6b0f1679031a)
Fixed in b2.2.3 1.20/1.20.1 (I haven't released it yet)

**Comment by MBatt1** [comment]
It looks like there's a recipe issue but that's on their end, idk how they generate the recipes but something's wrong with the olvite longsword, in case you want to open an issue over with them

```
[16:52:49] [Render thread/ERROR]: Parsing error loading recipe medievalweapons:olvite_long_sword
com.google.gson.JsonSyntaxException: Unknown item 'betterend:olvite'
	at net.minecraft.class_1869.method_17878(class_1869.java:272) ~[client-intermediary.jar:?]
	at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
	at net.minecraft.class_1869.method_8155(class_1869.java:272) ~[client-intermediary.jar:?]
	at net.minecraft.class_1856.method_8107(class_1856.java:160) ~[client-intermediary.jar:?]
	at net.minecraft.class_1856.method_8102(class_1856.java:143) ~[client-intermediary.jar:?]
	at net.minecraft.class_1869.method_8157(class_1869.java:252) ~[client-intermediary.jar:?]
	...
```

**Comment by TheShadyyOneYT** [comment]
Ok thank you! I will show them.

**Comment by MBatt1** [comment]
Just pushed 2.2.3 out, I'm closing this but please reopen if the mod loading still has issues!

**Comment by TheShadyyOneYT** [comment]
Good to hear! I will go ahead and get the message out, and to confirm, there isn't a crash anymore! I thank you very much for this fix :)
