### ISSUE TITLE
Bug: Mixin incompatibility with Random Mob Sizes version 2.1.1 for Minecraft 1.20.1

### ISSUE THREAD

**Issue by ThatKatNaps** [devs-immortal/The-Aether#808]
### What happened?

Install all dependencies and try launching, errors before load

Mixin error conflicting src/main/java/net/id/paradiselost/mixin/util/NbtCompoundAccessor.java from Paradise Lost with common/src/main/java/com/tristankechlo/random_mob_sizes/mixin from Random Mob Sizes

### Mod Version

2.2.3

### Fabric API Version

0.92.2+ 1.20.1

### Relevant log output

```Shell
[11:24:25] [main/ERROR]: Mixin apply for mod random_mob_sizes failed random_mob_sizes.mixins.json:CompoundTagInvoker from mod random_mob_sizes -> net.minecraft.class_2487: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException Incompatible @Invoker getEntries (for method_29143()Ljava/util/Map;) in random_mob_sizes.mixins.json:CompoundTagInvoker from mod random_mob_sizes previously written by net.id.paradiselost.mixin.util.NbtCompoundAccessor (for field_11515:Ljava/util/Map;) [ -> ACCESSOR Applicator Phase -> random_mob_sizes.mixins.json:CompoundTagInvoker from mod random_mob_sizes -> Apply Accessors]
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: Incompatible @Invoker getEntries (for method_29143()Ljava/util/Map;) in random_mob_sizes.mixins.json:CompoundTagInvoker from mod random_mob_sizes previously written by net.id.paradiselost.mixin.util.NbtCompoundAccessor (for field_11515:Ljava/util/Map;) [ -> ACCESSOR Applicator Phase -> random_mob_sizes.mixins.json:CompoundTagInvoker from mod random_mob_sizes -> Apply Accessors]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.isAlreadyMerged(MixinApplicatorStandard.java:578) ~[sponge-mixin-0.15.2+mixin.0.8.7.jar:0.15.2+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.mergeMethod(MixinApplicatorStandard.java:488) ~[sponge-mixin-0.15.2+mixin.0.8.7.jar:0.15.2+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyAccessors(MixinApplicatorStandard.java:764) ~[sponge-mixin-0.15.2+mixin.0.8.7.jar:0.15.2+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:320) ~[sponge-mixin-0.15.2+mixin.0.8.7.jar:0.15.2+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:246) ~[sponge-mixin-0.15.2+mixin.0.8.7.jar:0.15.2+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:437) ~[sponge-mixin-0.15.2+mixin.0.8.7.jar:0.15.2+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:418) ~[sponge-mixin-0.15.2+mixin.0.8.7.jar:0.15.2+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.15.2+mixin.0.8.7.jar:0.15.2+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.15.2+mixin.0.8.7.jar:0.15.2+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.15.2+mixin.0.8.7.jar:0.15.2+mixin.0.8.7]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.16.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.16.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.16.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.16.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	at net.minecraft.class_1799.method_28376(class_1799.java:82) ~[client-intermediary.jar:?]
	at com.mojang.serialization.codecs.RecordCodecBuilder.create(RecordCodecBuilder.java:72) ~[datafixerupper-6.0.8.jar:?]
	at net.minecraft.class_1799.<clinit>(class_1799.java:80) ~[client-intermediary.jar:?]
	at net.minecraft.class_3727.<clinit>(class_3727.java:16) ~[client-intermediary.jar:?]
	at net.minecraft.class_3726.method_16194(class_3726.java:10) ~[client-intermediary.jar:?]
	at net.minecraft.class_4970$class_4971.method_26218(class_4970.java:1028) ~[client-intermediary.jar:?]
	at net.minecraft.class_2248.method_9579(class_2248.java:309) ~[client-intermediary.jar:?]
	at net.minecraft.class_4970$class_4971$class_3752.<init>(class_4970.java:1281) ~[client-intermediary.jar:?]
	at net.minecraft.class_4970$class_4971.method_26200(class_4970.java:843) ~[client-intermediary.jar:?]
	at net.minecraft.class_2246.<clinit>(class_2246.java:1185) ~[client-intermediary.jar:?]
	at net.minecraft.class_2358.method_10199(class_2358.java:326) ~[client-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:54) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:166) ~[minecraft-1.20.1-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) ~[fabric-loader-0.16.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.16.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.16.3.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243) ~[NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278) ~[NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) ~[NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) ~[NewLaunch.jar:?]
```

### Other mods

Too big for zip send

Using 
paradise-lost-2.2.3-beta+1.20.0.jar
cloth-config-11.1.118-fabric.jar
randommobsizes-fabric-1.20.1-2.1.1.jar
fabric-api-0.92.2+1.20.1.jar

### Additional Information

Using MultiMC

**Comment by MBatt1** [comment]
Resolved in Beta 2.2.4+, please reopen if the issue persists! Thanks!
