### ISSUE TITLE
Bug: Cannot enchant PL equipment

### ISSUE THREAD

**Issue by MBatt1** [devs-immortal/The-Aether#814]
### What happened?

Title is self-explanatory.

### Mod Version

Beta 2.2.4 (1.20.3)

### Relevant log output

```Shell
---- Minecraft Crash Report ----
// You're mean.

Time: 2024-09-24 09:58:16
Description: Container click

java.lang.ClassCastException: class net.id.paradiselost.items.utils.IngredientUtil$$Lambda$10166/0x0000000801242218 cannot be cast to class net.minecraft.class_1856 (net.id.paradiselost.items.utils.IngredientUtil$$Lambda$10166/0x0000000801242218 and net.minecraft.class_1856 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @55040f2f)
	at net.id.paradiselost.items.tools.ParadiseLostToolMaterials$ParadiseToolMaterial.method_8023(ParadiseLostToolMaterials.java:65)
	at net.minecraft.class_1831.method_7878(class_1831.java:22)
	at net.minecraft.class_1706.method_24928(class_1706.java:162)
	at net.minecraft.class_4861.method_7609(class_4861.java:106)
	at net.minecraft.class_4861$3.method_5431(class_4861.java:96)
	at net.minecraft.class_1277.redirect$zoa000$fabric-transfer-api-v1$fabric_redirectMarkDirty(class_1277.java:543)
	at net.minecraft.class_1277.method_5447(class_1277.java:144)
	at net.minecraft.class_1735.method_7673(class_1735.java:75)
	at net.minecraft.class_1735.method_48931(class_1735.java:66)
	at net.minecraft.class_1735.method_53512(class_1735.java:63)
	at net.minecraft.class_1735.method_32755(class_1735.java:160)
	at net.minecraft.class_1703.method_30010(class_1703.java:412)
	at net.minecraft.class_1703.method_7593(class_1703.java:294)
	at net.minecraft.class_636.method_2906(class_636.java:448)
	at net.minecraft.class_465.method_2383(class_465.java:557)
	at net.minecraft.class_465.method_25406(class_465.java:521)
	at net.minecraft.class_312.method_1605(class_312.java:101)
	at net.minecraft.class_437.method_25412(class_437.java:414)
	at net.minecraft.class_312.method_1601(class_312.java:101)
	at net.minecraft.class_312.method_22686(class_312.java:180)
	at net.minecraft.class_1255.execute(class_1255.java:102)
	at net.minecraft.class_312.method_22684(class_312.java:180)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3438)
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:202)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:213)
	at net.minecraft.class_1041.method_15998(class_1041.java:287)
	at net.minecraft.class_310.method_1523(class_310.java:1349)
	at net.minecraft.class_310.method_1514(class_310.java:888)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.id.paradiselost.items.tools.ParadiseLostToolMaterials$ParadiseToolMaterial.method_8023(ParadiseLostToolMaterials.java:65)
	at net.minecraft.class_1831.method_7878(class_1831.java:22)
	at net.minecraft.class_1706.method_24928(class_1706.java:162)
	at net.minecraft.class_4861.method_7609(class_4861.java:106)
	at net.minecraft.class_4861$3.method_5431(class_4861.java:96)
	at net.minecraft.class_1277.redirect$zoa000$fabric-transfer-api-v1$fabric_redirectMarkDirty(class_1277.java:543)
	at net.minecraft.class_1277.method_5447(class_1277.java:144)
	at net.minecraft.class_1735.method_7673(class_1735.java:75)
	at net.minecraft.class_1735.method_48931(class_1735.java:66)
	at net.minecraft.class_1735.method_53512(class_1735.java:63)
	at net.minecraft.class_1735.method_32755(class_1735.java:160)
	at net.minecraft.class_1703.method_30010(class_1703.java:412)
	at net.minecraft.class_1703.method_7593(class_1703.java:294)
	at net.minecraft.class_636.method_2906(class_636.java:448)
	at net.minecraft.class_465.method_2383(class_465.java:557)
	at net.minecraft.class_465.method_25406(class_465.java:521)
	at net.minecraft.class_312.method_1605(class_312.java:101)
	at net.minecraft.class_437.method_25412(class_437.java:414)
	at net.minecraft.class_312.method_1601(class_312.java:101)
	at net.minecraft.class_312.method_22686(class_312.java:180)
	at net.minecraft.class_1255.execute(class_1255.java:102)
	at net.minecraft.class_312.method_22684(class_312.java:180)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3438)
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:202)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:213)

-- Click info --
Details:
	Menu Type: minecraft:anvil
	Menu Class: net.minecraft.class_1706
	Slot Count: 39
	Slot: 1
	Button: 0
	Type: PICKUP
Stacktrace:
	at net.minecraft.class_1703.method_7593(class_1703.java:294)
	at net.minecraft.class_636.method_2906(class_636.java:448)
	at net.minecraft.class_465.method_2383(class_465.java:557)
	at net.minecraft.class_465.method_25406(class_465.java:521)
	at net.minecraft.class_312.method_1605(class_312.java:101)
	at net.minecraft.class_437.method_25412(class_437.java:414)
	at net.minecraft.class_312.method_1601(class_312.java:101)
	at net.minecraft.class_312.method_22686(class_312.java:180)
	at net.minecraft.class_1255.execute(class_1255.java:102)
	at net.minecraft.class_312.method_22684(class_312.java:180)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3438)
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:202)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:213)
	at net.minecraft.class_1041.method_15998(class_1041.java:287)
	at net.minecraft.class_310.method_1523(class_310.java:1349)
	at net.minecraft.class_310.method_1514(class_310.java:888)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected screen --
Details:
	Screen name: net.minecraft.class_471
Stacktrace:
	at net.minecraft.class_437.method_25412(class_437.java:414)
	at net.minecraft.class_312.method_1601(class_312.java:101)
	at net.minecraft.class_312.method_22686(class_312.java:180)
	at net.minecraft.class_1255.execute(class_1255.java:102)
	at net.minecraft.class_312.method_22684(class_312.java:180)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3438)
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:202)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:213)
	at net.minecraft.class_1041.method_15998(class_1041.java:287)
	at net.minecraft.class_310.method_1523(class_310.java:1349)
	at net.minecraft.class_310.method_1514(class_310.java:888)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Uptime --
Details:
	JVM uptime: 54.594s
	Wall uptime: 47.191s
	High-res time: 45.948s
	Client ticks: 795 ticks / 39.750s
Stacktrace:
	at net.minecraft.class_310.method_1587(class_310.java:2564)
	at net.minecraft.class_310.method_54580(class_310.java:995)
	at net.minecraft.class_310.method_1514(class_310.java:908)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 1 total; [class_746['LeifTea'/431, l='ClientLevel', x=-5.77, y=80.00, z=2.91]]
	Chunk stats: 961, 609
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,97,0), Section: (at 0,1,0 in 0,6,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 1139 game time, 1139 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
	Tracked entity count: 230

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric, cardinal-components-base, cardinal-components-entity, cloth-config, customportalapi, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-containers-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-events-lifecycle-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-message-api-v1, fabric-mining-level-api-v1, fabric-model-loading-api-v1, fabric-models-v0, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, mm, paradise_lost

-- System Details --
Details:
	Minecraft Version: 1.20.4
	Minecraft Version ID: 1.20.4
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.8, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 2277251208 bytes (2171 MiB) / 3401580544 bytes (3244 MiB) up to 5972688896 bytes (5696 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 3600 6-Core Processor              
	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
	Microarchitecture: Zen 2
	Frequency (GHz): 3.59
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: Virtual Desktop Monitor
	Graphics card #0 vendor: Virtual Desktop, Inc.
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: DriverVersion=13.50.53.699
	Graphics card #1 name: NVIDIA GeForce GTX 1060 3GB
	Graphics card #1 vendor: NVIDIA (0x10de)
	Graphics card #1 VRAM (MB): 3072.00
	Graphics card #1 deviceId: 0x1c02
	Graphics card #1 versionInfo: DriverVersion=32.0.15.5612
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.60
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.60
	Memory slot #1 type: DDR4
	Memory slot #2 capacity (MB): 8192.00
	Memory slot #2 clockSpeed (GHz): 3.60
	Memory slot #2 type: DDR4
	Memory slot #3 capacity (MB): 8192.00
	Memory slot #3 clockSpeed (GHz): 3.60
	Memory slot #3 type: DDR4
	Virtual memory max (MB): 37535.09
	Virtual memory used (MB): 16555.97
	Swap memory total (MB): 4864.00
	Swap memory used (MB): 2.35
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx5696m -Xms256m
	Fabric Mods: 
		cloth-config: Cloth Config v13 13.0.138
			cloth-basic-math: cloth-basic-math 0.6.1
		fabric-api: Fabric API 0.97.2+1.20.4
			fabric-api-base: Fabric API Base 0.4.37+78d798af4f
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.50+82b1bb3e4f
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.17+78d798af4f
			fabric-block-api-v1: Fabric Block API (v1) 1.0.17+3e2216cb4f
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.5+78d798af4f
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.47+78d798af4f
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.8+78d798af4f
			fabric-command-api-v1: Fabric Command API (v1) 1.2.42+f71b366f4f
			fabric-command-api-v2: Fabric Command API (v2) 2.2.21+78d798af4f
			fabric-commands-v0: Fabric Commands (v0) 0.2.59+df3654b34f
			fabric-containers-v0: Fabric Containers (v0) 0.1.88+df3654b34f
			fabric-content-registries-v0: Fabric Content Registries (v0) 5.0.16+78d798af4f
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.11+78d798af4f
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.24+78d798af4f
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.5+b90db5744f
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 13.2.6+5c0133444f
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.63+6605d1a84f
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.2+09fc25014f
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.2+389931eb4f
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.75+df3654b34f
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.47+78d798af4f
			fabric-item-api-v1: Fabric Item API (v1) 2.3.0+bcdd12964f
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.27+ee30b13a4f
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.42+78d798af4f
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.40+df3654b34f
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.1+a67ffb5d4f
			fabric-loot-api-v2: Fabric Loot API (v2) 2.1.10+78d798af4f
			fabric-message-api-v1: Fabric Message API (v1) 6.0.6+78d798af4f
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.66+78d798af4f
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.9+78d798af4f
			fabric-models-v0: Fabric Models (v0) 0.4.8+9386d8a74f
			fabric-networking-api-v1: Fabric Networking API (v1) 3.1.9+6abb6a4b4f
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 13.1.0+dba1195c4f
			fabric-particles-v1: Fabric Particles (v1) 1.1.8+78d798af4f
			fabric-recipe-api-v1: Fabric Recipe API (v1) 2.0.22+78d798af4f
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 4.0.21+ee30b13a4f
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.5+78d798af4f
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.6+d331d3144f
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.54+df3654b34f
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.43+73761d2e4f
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.2+e761c6694f
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.57+df3654b34f
			fabric-rendering-v1: Fabric Rendering (v1) 3.2.1+6fd945a04f
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.15+78d798af4f
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.21+ee30b13a4f
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.18+78d798af4f
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.57+78d798af4f
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.18+78d798af4f
			fabric-transfer-api-v1: Fabric Transfer API (v1) 4.0.12+90f2d7b14f
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 5.0.15+78d798af4f
		fabricloader: Fabric Loader 0.16.5
			mixinextras: MixinExtras 0.4.1
		java: OpenJDK 64-Bit Server VM 17
		minecraft: Minecraft 1.20.4
		paradise_lost: Paradise Lost 2.2.4-beta+1.20.3
			cardinal-components-base: Cardinal Components API (base) 5.3.0
			cardinal-components-entity: Cardinal Components API (entities) 5.3.0
			customportalapi: Custom Portal Api 0.0.1-beta65-1.20.4
			mm: Manningham Mills 2.3
	Launched Version: fabric-loader-0.16.5-1.20.4
	Launcher name: minecraft-launcher
	Backend library: LWJGL version 3.3.2-snapshot
	Backend API: NVIDIA GeForce GTX 1060 3GB/PCIe/SSE2 GL version 3.2.0 NVIDIA 556.12, NVIDIA Corporation
	Window size: 1024x768
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Universe: 400921fb54442d18
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Render Distance: 12/12 chunks
	Resource Packs: fabric
	Current Language: en_us
	Locale: en_US
	CPU: 12x AMD Ryzen 5 3600 6-Core Processor 
	Server Running: true
	Player Count: 1 / 8; [class_3222['LeifTea'/431, l='ServerLevel[New World]', x=-5.77, y=80.00, z=2.91]]
	Data Packs: vanilla, fabric, fabric-convention-tags-v1, paradise_lost (incompatible)
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Experimental
```

**Comment by MBatt1** [comment]
Resolved in 2.2.5+ on 1.20.3 and higher (older versions don't seem to have this issue)
